version: 2
jobs:
  build:
    machine:
      image: &circleci_image circleci/classic:edge
    working_directory: &wd ~/repo
    steps:
      - checkout
      # - run:
      #     name: docker-compose build
      #     command: |
      #       set -x
      #       docker-compose build
      # - run:
      #     name: cp env
      #     command: cp frontend/.env.default frontend/.env && cp .env.default .env && cp api/src/.env.default api/src/.env

  test:
    machine:
      image: *circleci_image
    working_directory: *wd
    steps:
      - checkout
      # - run:
      #     name: docker-compose build
      #     command: |
      #       set -x
      #       docker-compose build
      # - run:
      #     name: docker-compose run --rm api rspec
      #     command: |
      #       set -x
      #       docker-compose run --rm api rspec
      # - run:
      #     name: docker-compose down
      #     command: docker-compose down
  staticAnalysisApi:
    machine:
      image: *circleci_image
    working_directory: *wd
    steps:
      - checkout
  # test:
  # staticAnalysisFrontend:

# $ cp frontend/.env.default frontend/.env && cp .env.default .env && cp api/src/.env.default api/src/.env
# $ docker-compose build
# $ docker-compose run --rm api bundle install
# $ docker-compose up
#

workflows:
  version: 2
  test_and_analyse:
    jobs:
      - build
      - test:
          requires:
            - build
      - staticAnalysisApi:
          requires:
            - build
